### PR TITLE
Throwing exception when an invalid XML character is being saved into Infoset (Lombiq Technologies: ORCH-208), fixes #7560

### LINKED ISSUE #7560: Special characters can break infoset
If you try to save a special character (know about [vertical tab](https://en.wikipedia.org/wiki/Control_character) but surely this is not the only one) to an infoset-backed but also record-stored content part then you can cause a YSOD only fixable by editing the DB. Such a character can mess up the infoset's XML, resulting in the below exception being thrown.

```
2017-02-07 04:33:07,785 [15] Orchard.ContentManagement.DefaultContentManager - (null) - ArgumentException thrown from IContentHandler by Orchard.ContentManagement.FieldStorage.InfosetStorage.InfosetHandler [(null)]
System.ArgumentException: '', hexadecimal value 0x0B, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at Orchard.ContentManagement.FieldStorage.InfosetStorage.Infoset.get_Data()
   at Orchard.ContentManagement.FieldStorage.InfosetStorage.InfosetHandler.Creating(CreateContentContext context)
   at Orchard.ContentManagement.DefaultContentManager.<>c__DisplayClass41_0.<Create>b__0(IContentHandler handler)
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger)
```

The offending character will be saved to the record's field but it won't succeed getting into the infoset, thus this write operation will be retried forever, without success. I guess that if there's no record then just saving the item would fail.

We should probably do some encoding in `InfosetHelper.Store()`? Note that I experienced this with `TitlePart`, so maybe it's only affecting infoset values if they're stored in an attribute like in this case.

### PR DESCRIPTION
**Pull request by Piedone**
Implements the fix discussed under https://github.com/OrchardCMS/Orchard/issues/7560.

This exception will be logged if you try to write to the Infoset (or Infoset-backed properties) directly from code, but if you're editing a content item you'll be greated with a validation error something like this:
image

As you can see this is far from ideal since there is no error message in the validation error box. This is because exception arising during model property validation it seems are not displayed. I don't know a simple way to solve this (nor do I think just displaying exceptions would the be best solution). However, I think this right now is "good enough": you can't break your site at least.

### CODE REVIEW

**Comment by sebastienros** [comment]
Or at least in the BodyPart search the content for special chars and invalidate it?

**Comment by Piedone** [comment]
> Or at least in the BodyPart search the content for special chars and invalidate it?

Well, we could add this validation specifically in its driver. Is this what you mean?

**Comment by BenedekFarkas** [comment]
@sebastienros changes are good to go? Also see https://github.com/OrchardCMS/Orchard/issues/7560#issuecomment-495351855.

File: src/Orchard/ContentManagement/InfosetHelper.cs [hunk 1]
```diff
@@ -129,5 +132,23 @@ public static class InfosetHelper {
...
+
+        /// <summary>
+        /// Checks the given string and throws an <see cref="ArgumentException"/> if it contains characters that are
+        /// invalid in XML. Otherwise just returns the original string.
+        /// </summary>
+        /// <param name="value">The string to check for invalid XML characters.</param>
+        /// <exception cref="ArgumentException">Thrown if the string contains invalid characters.</exception>
+        /// <returns>The original string if no invalid characters were found.</returns>
+        public static string ThrowIfContainsInvalidXmlCharacter(string value) {
+            var invalidCharacters = value.Intersect(InvalidXmlCharacters);
```
Comment (sebastienros) [inline src/Orchard/ContentManagement/InfosetHelper.cs]: The intersect will process the whole document. I assume we could fail on the first occurrence. It's not a hot path though, so it doesn't really matter, not blocking the PR.

**Review by sebastienros — APPROVED** [review]

File: src/Orchard/ContentManagement/InfosetHelper.cs (hunk 1 above)
Comment (Piedone) [reply src/Orchard/ContentManagement/InfosetHelper.cs]: Yeah, I thought about it. The idea was to give the user a more helpful error message by listing all offending characters instead of just the first one. Now this doesn't help much actually with no proper error message being displayed...

**Comment by Piedone** [comment]
I changed how the validation works and now it fails on the first character.

I also tried to add custom validation just for the body part but couldn't yet find a way and wouldn't really want to spend more time on this:

- Due to the exception in `InfosetHelper` down the line the viewmodel will be empty in the driver after it's updated, so the body text can't be checked there.
- I created a custom validation attribute, see below, and put it onto `BodyEditorViewModel.Text`. It runs correctly but its validation message is not displayed anywhere. As mentioned before the validation summary is displayed empty, so this gets lost somewhere too (and it's not displayed where validation messages for `BodyEditorViewModel.Text`) are explicitly displayed in the *Parts.Common.Body.cshtml* editor.

```c#
    /// <summary>
    /// Attribute to be put on models' properties to check the input against invalid XML characters (or more precisely,
    /// invalid XML characters that aren't handled by the .NET XML types and thus would break Infoset storage).
    /// </summary>
    public class ValidateXmlAttribute : ValidationAttribute {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext) {
            if (value == null) {
                return ValidationResult.Success;
            }

            var invalidXmlCharacters = value.ToString().Intersect(InfosetHelper.InvalidXmlCharacters);

            if (invalidXmlCharacters.Any()) {
                return new ValidationResult(
                    $"The field {validationContext.DisplayName} contains the character(s) {string.Join(", ", invalidXmlCharacters.Select(character => character.ToString()))} which are invalid in XML and should be removed.");
            }

            return ValidationResult.Success;
        }
    }
```
