### PR TITLE
7919: The Alias UI links for sites using UrlPrefix are broken

### LINKED ISSUE #7919: The Alias UI links for sites using UrlPrefix are broken
The UrlPrefix is manually added to the alias and root urls  but the helper methods do that automatically so the links are broken

### PR DESCRIPTION
**Pull request by Hazzamanic**
Fixes https://github.com/OrchardCMS/Orchard/issues/7919. Also reverting this commit's changes to the Href method (https://github.com/OrchardCMS/Orchard/commit/9c2ea8067094d9ed02f50bcd372bf445ff2e81ee#diff-3806ff11c9d923fac04777c83296a19e) that overrode this commit https://github.com/OrchardCMS/Orchard/commit/a4894930f054fa9521fb4ea98594dd60fea72152 that fixed this issue https://github.com/OrchardCMS/Orchard/issues/4540

### CODE REVIEW

**Comment by sebastienros** [comment]
Looks good, but can someone try it and confirm it fixes the issue? I am worried as the code explicitly handled the prefix.

**Comment by BenedekFarkas** [comment]
@sebastienros tested and slightly adjusted, good to go!

**Review by sebastienros — APPROVED** [review]

File: src/Orchard/Mvc/ViewEngines/Razor/WebViewPage.cs [hunk 1]
```diff
@@ -190,11 +190,10 @@ public abstract class WebViewPage<TModel> : System.Web.Mvc.WebViewPage<TModel>,
...
 
-            if (!String.IsNullOrEmpty(_tenantPrefix)
-                && path.StartsWith("~/")  
-                && !CommonLocations.Any(gpp=>path.StartsWith(gpp, StringComparison.OrdinalIgnoreCase))
-            ) { 
-                    return base.Href("~/" + _tenantPrefix + path.Substring(2), pathParts);
+            if (!string.IsNullOrWhiteSpace(_tenantPrefix)
+                && path.StartsWith("~/")
+                && !CommonLocations.Any(gpp => path.StartsWith(gpp, StringComparison.OrdinalIgnoreCase))) {
+                return base.Href("~/" + _tenantPrefix + path.Substring(1), pathParts);
```
Comment (AndreaPiovanelli) [inline src/Orchard/Mvc/ViewEngines/Razor/WebViewPage.cs:196]: Why is the substring start index parameter changed?
Since code gets to line 196 only if path starts with ~, it stripped ~/ in the previous version of the file; now it only strips the ~ character: is it correct keeping the / character?

Comment (BenedekFarkas) [reply src/Orchard/Mvc/ViewEngines/Razor/WebViewPage.cs:196]: FYI this is only applied if there is a tenant prefix. e.g., the base URL is `mysite.com/mytenant`. In this case you still need the `/` between the tenant prefix and the rest of the path. Without this change all the Hrefs were broken if you provided a path that started with `~/` when there's a tenant prefix.
